---
title: La portée des fonctions Python
hero_image: images/banner.png
description: Apprendre la portée des variables dans les fonctions
original_url:
theme: red
duration: 1 #1, 2 or 3
ingredient: true
listed: false
copyedit: true
interests:
technologies: "python"
steps:
  - 
    title: Qu'est-ce que la portée ?
